// Copyright the Hyperledger Fabric contributors. All rights reserved.
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.23.4
// source: elect.proto

package pbgo

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Vote_Role int32

const (
	Vote_COMMON_PEOPLE     Vote_Role = 0
	Vote_MEM_PARTY         Vote_Role = 1
	Vote_DEPUTY_TO_NPC     Vote_Role = 2
	Vote_MEM_NPC_PRESI     Vote_Role = 3
	Vote_MEM_NPC_COMMITTEE Vote_Role = 4
)

// Enum value maps for Vote_Role.
var (
	Vote_Role_name = map[int32]string{
		0: "COMMON_PEOPLE",
		1: "MEM_PARTY",
		2: "DEPUTY_TO_NPC",
		3: "MEM_NPC_PRESI",
		4: "MEM_NPC_COMMITTEE",
	}
	Vote_Role_value = map[string]int32{
		"COMMON_PEOPLE":     0,
		"MEM_PARTY":         1,
		"DEPUTY_TO_NPC":     2,
		"MEM_NPC_PRESI":     3,
		"MEM_NPC_COMMITTEE": 4,
	}
)

func (x Vote_Role) Enum() *Vote_Role {
	p := new(Vote_Role)
	*p = x
	return p
}

func (x Vote_Role) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Vote_Role) Descriptor() protoreflect.EnumDescriptor {
	return file_elect_proto_enumTypes[0].Descriptor()
}

func (Vote_Role) Type() protoreflect.EnumType {
	return &file_elect_proto_enumTypes[0]
}

func (x Vote_Role) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Vote_Role.Descriptor instead.
func (Vote_Role) EnumDescriptor() ([]byte, []int) {
	return file_elect_proto_rawDescGZIP(), []int{1, 0}
}

// import "common/common.proto";
// 任期
type Term struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	T int32  `protobuf:"varint,1,opt,name=t,proto3" json:"t,omitempty"`
	S string `protobuf:"bytes,2,opt,name=s,proto3" json:"s,omitempty"`
	E string `protobuf:"bytes,3,opt,name=e,proto3" json:"e,omitempty"`
}

func (x *Term) Reset() {
	*x = Term{}
	if protoimpl.UnsafeEnabled {
		mi := &file_elect_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Term) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Term) ProtoMessage() {}

func (x *Term) ProtoReflect() protoreflect.Message {
	mi := &file_elect_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Term.ProtoReflect.Descriptor instead.
func (*Term) Descriptor() ([]byte, []int) {
	return file_elect_proto_rawDescGZIP(), []int{0}
}

func (x *Term) GetT() int32 {
	if x != nil {
		return x.T
	}
	return 0
}

func (x *Term) GetS() string {
	if x != nil {
		return x.S
	}
	return ""
}

func (x *Term) GetE() string {
	if x != nil {
		return x.E
	}
	return ""
}

type Vote struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Voter     string    `protobuf:"bytes,2,opt,name=voter,proto3" json:"voter,omitempty"`
	Pubkey    string    `protobuf:"bytes,3,opt,name=pubkey,proto3" json:"pubkey,omitempty"`
	Id        string    `protobuf:"bytes,4,opt,name=id,proto3" json:"id,omitempty"`
	Role      Vote_Role `protobuf:"varint,5,opt,name=role,proto3,enum=pbgo.Vote_Role" json:"role,omitempty"`
	Term      *Term     `protobuf:"bytes,6,opt,name=term,proto3" json:"term,omitempty"`
	Signature string    `protobuf:"bytes,7,opt,name=signature,proto3" json:"signature,omitempty"`
}

func (x *Vote) Reset() {
	*x = Vote{}
	if protoimpl.UnsafeEnabled {
		mi := &file_elect_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Vote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vote) ProtoMessage() {}

func (x *Vote) ProtoReflect() protoreflect.Message {
	mi := &file_elect_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vote.ProtoReflect.Descriptor instead.
func (*Vote) Descriptor() ([]byte, []int) {
	return file_elect_proto_rawDescGZIP(), []int{1}
}

func (x *Vote) GetVoter() string {
	if x != nil {
		return x.Voter
	}
	return ""
}

func (x *Vote) GetPubkey() string {
	if x != nil {
		return x.Pubkey
	}
	return ""
}

func (x *Vote) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Vote) GetRole() Vote_Role {
	if x != nil {
		return x.Role
	}
	return Vote_COMMON_PEOPLE
}

func (x *Vote) GetTerm() *Term {
	if x != nil {
		return x.Term
	}
	return nil
}

func (x *Vote) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

type BallotResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status int32  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Msg    string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data   []byte `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *BallotResponse) Reset() {
	*x = BallotResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_elect_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BallotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BallotResponse) ProtoMessage() {}

func (x *BallotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_elect_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BallotResponse.ProtoReflect.Descriptor instead.
func (*BallotResponse) Descriptor() ([]byte, []int) {
	return file_elect_proto_rawDescGZIP(), []int{2}
}

func (x *BallotResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *BallotResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *BallotResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type Identity struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Id   string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Ip   string `protobuf:"bytes,3,opt,name=ip,proto3" json:"ip,omitempty"`
}

func (x *Identity) Reset() {
	*x = Identity{}
	if protoimpl.UnsafeEnabled {
		mi := &file_elect_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Identity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Identity) ProtoMessage() {}

func (x *Identity) ProtoReflect() protoreflect.Message {
	mi := &file_elect_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Identity.ProtoReflect.Descriptor instead.
func (*Identity) Descriptor() ([]byte, []int) {
	return file_elect_proto_rawDescGZIP(), []int{3}
}

func (x *Identity) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Identity) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Identity) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

type Empt struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empt) Reset() {
	*x = Empt{}
	if protoimpl.UnsafeEnabled {
		mi := &file_elect_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empt) ProtoMessage() {}

func (x *Empt) ProtoReflect() protoreflect.Message {
	mi := &file_elect_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empt.ProtoReflect.Descriptor instead.
func (*Empt) Descriptor() ([]byte, []int) {
	return file_elect_proto_rawDescGZIP(), []int{4}
}

type ListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Num int32       `protobuf:"varint,1,opt,name=num,proto3" json:"num,omitempty"`
	Ids []*Identity `protobuf:"bytes,2,rep,name=ids,proto3" json:"ids,omitempty"`
}

func (x *ListResponse) Reset() {
	*x = ListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_elect_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponse) ProtoMessage() {}

func (x *ListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_elect_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResponse.ProtoReflect.Descriptor instead.
func (*ListResponse) Descriptor() ([]byte, []int) {
	return file_elect_proto_rawDescGZIP(), []int{5}
}

func (x *ListResponse) GetNum() int32 {
	if x != nil {
		return x.Num
	}
	return 0
}

func (x *ListResponse) GetIds() []*Identity {
	if x != nil {
		return x.Ids
	}
	return nil
}

type CalloutVoteResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Form []byte `protobuf:"bytes,1,opt,name=form,proto3" json:"form,omitempty"`
}

func (x *CalloutVoteResponse) Reset() {
	*x = CalloutVoteResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_elect_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CalloutVoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalloutVoteResponse) ProtoMessage() {}

func (x *CalloutVoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_elect_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalloutVoteResponse.ProtoReflect.Descriptor instead.
func (*CalloutVoteResponse) Descriptor() ([]byte, []int) {
	return file_elect_proto_rawDescGZIP(), []int{6}
}

func (x *CalloutVoteResponse) GetForm() []byte {
	if x != nil {
		return x.Form
	}
	return nil
}

type CheckVoteBoxResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Form []byte `protobuf:"bytes,1,opt,name=form,proto3" json:"form,omitempty"`
}

func (x *CheckVoteBoxResponse) Reset() {
	*x = CheckVoteBoxResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_elect_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckVoteBoxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckVoteBoxResponse) ProtoMessage() {}

func (x *CheckVoteBoxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_elect_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckVoteBoxResponse.ProtoReflect.Descriptor instead.
func (*CheckVoteBoxResponse) Descriptor() ([]byte, []int) {
	return file_elect_proto_rawDescGZIP(), []int{7}
}

func (x *CheckVoteBoxResponse) GetForm() []byte {
	if x != nil {
		return x.Form
	}
	return nil
}

var File_elect_proto protoreflect.FileDescriptor

var file_elect_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x70,
	0x62, 0x67, 0x6f, 0x22, 0x30, 0x0a, 0x04, 0x54, 0x65, 0x72, 0x6d, 0x12, 0x0c, 0x0a, 0x01, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x74, 0x12, 0x0c, 0x0a, 0x01, 0x73, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x01, 0x73, 0x12, 0x0c, 0x0a, 0x01, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x01, 0x65, 0x22, 0x8e, 0x02, 0x0a, 0x04, 0x56, 0x6f, 0x74, 0x65, 0x12, 0x14,
	0x0a, 0x05, 0x76, 0x6f, 0x74, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76,
	0x6f, 0x74, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x75, 0x62, 0x6b, 0x65, 0x79, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x75, 0x62, 0x6b, 0x65, 0x79, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x23, 0x0a, 0x04,
	0x72, 0x6f, 0x6c, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0f, 0x2e, 0x70, 0x62, 0x67,
	0x6f, 0x2e, 0x56, 0x6f, 0x74, 0x65, 0x2e, 0x52, 0x6f, 0x6c, 0x65, 0x52, 0x04, 0x72, 0x6f, 0x6c,
	0x65, 0x12, 0x1e, 0x0a, 0x04, 0x74, 0x65, 0x72, 0x6d, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0a, 0x2e, 0x70, 0x62, 0x67, 0x6f, 0x2e, 0x54, 0x65, 0x72, 0x6d, 0x52, 0x04, 0x74, 0x65, 0x72,
	0x6d, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x22,
	0x65, 0x0a, 0x04, 0x52, 0x6f, 0x6c, 0x65, 0x12, 0x11, 0x0a, 0x0d, 0x43, 0x4f, 0x4d, 0x4d, 0x4f,
	0x4e, 0x5f, 0x50, 0x45, 0x4f, 0x50, 0x4c, 0x45, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x4d, 0x45,
	0x4d, 0x5f, 0x50, 0x41, 0x52, 0x54, 0x59, 0x10, 0x01, 0x12, 0x11, 0x0a, 0x0d, 0x44, 0x45, 0x50,
	0x55, 0x54, 0x59, 0x5f, 0x54, 0x4f, 0x5f, 0x4e, 0x50, 0x43, 0x10, 0x02, 0x12, 0x11, 0x0a, 0x0d,
	0x4d, 0x45, 0x4d, 0x5f, 0x4e, 0x50, 0x43, 0x5f, 0x50, 0x52, 0x45, 0x53, 0x49, 0x10, 0x03, 0x12,
	0x15, 0x0a, 0x11, 0x4d, 0x45, 0x4d, 0x5f, 0x4e, 0x50, 0x43, 0x5f, 0x43, 0x4f, 0x4d, 0x4d, 0x49,
	0x54, 0x54, 0x45, 0x45, 0x10, 0x04, 0x22, 0x4e, 0x0a, 0x0e, 0x42, 0x61, 0x6c, 0x6c, 0x6f, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d,
	0x73, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x3e, 0x0a, 0x08, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69,
	0x74, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x70, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x70, 0x22, 0x06, 0x0a, 0x04, 0x45, 0x6d, 0x70, 0x74, 0x22, 0x42,
	0x0a, 0x0c, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10,
	0x0a, 0x03, 0x6e, 0x75, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x6e, 0x75, 0x6d,
	0x12, 0x20, 0x0a, 0x03, 0x69, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e,
	0x70, 0x62, 0x67, 0x6f, 0x2e, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x52, 0x03, 0x69,
	0x64, 0x73, 0x22, 0x29, 0x0a, 0x13, 0x43, 0x61, 0x6c, 0x6c, 0x6f, 0x75, 0x74, 0x56, 0x6f, 0x74,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x6f, 0x72,
	0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x66, 0x6f, 0x72, 0x6d, 0x22, 0x2a, 0x0a,
	0x14, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x56, 0x6f, 0x74, 0x65, 0x42, 0x6f, 0x78, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x6f, 0x72, 0x6d, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x04, 0x66, 0x6f, 0x72, 0x6d, 0x32, 0x86, 0x02, 0x0a, 0x05, 0x45, 0x6c,
	0x65, 0x63, 0x74, 0x12, 0x2c, 0x0a, 0x06, 0x42, 0x61, 0x6c, 0x6c, 0x6f, 0x74, 0x12, 0x0a, 0x2e,
	0x70, 0x62, 0x67, 0x6f, 0x2e, 0x56, 0x6f, 0x74, 0x65, 0x1a, 0x14, 0x2e, 0x70, 0x62, 0x67, 0x6f,
	0x2e, 0x42, 0x61, 0x6c, 0x6c, 0x6f, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x12, 0x33, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79,
	0x12, 0x0e, 0x2e, 0x70, 0x62, 0x67, 0x6f, 0x2e, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79,
	0x1a, 0x12, 0x2e, 0x70, 0x62, 0x67, 0x6f, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x28, 0x0a, 0x04, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x0a,
	0x2e, 0x70, 0x62, 0x67, 0x6f, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x1a, 0x12, 0x2e, 0x70, 0x62, 0x67,
	0x6f, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x12, 0x36, 0x0a, 0x0b, 0x43, 0x61, 0x6c, 0x6c, 0x6f, 0x75, 0x74, 0x56, 0x6f, 0x74, 0x65, 0x12,
	0x0a, 0x2e, 0x70, 0x62, 0x67, 0x6f, 0x2e, 0x56, 0x6f, 0x74, 0x65, 0x1a, 0x19, 0x2e, 0x70, 0x62,
	0x67, 0x6f, 0x2e, 0x43, 0x61, 0x6c, 0x6c, 0x6f, 0x75, 0x74, 0x56, 0x6f, 0x74, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x38, 0x0a, 0x0c, 0x43, 0x68, 0x65, 0x63,
	0x6b, 0x56, 0x6f, 0x74, 0x65, 0x42, 0x6f, 0x78, 0x12, 0x0a, 0x2e, 0x70, 0x62, 0x67, 0x6f, 0x2e,
	0x56, 0x6f, 0x74, 0x65, 0x1a, 0x1a, 0x2e, 0x70, 0x62, 0x67, 0x6f, 0x2e, 0x43, 0x68, 0x65, 0x63,
	0x6b, 0x56, 0x6f, 0x74, 0x65, 0x42, 0x6f, 0x78, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x42, 0x16, 0x0a, 0x0c, 0x6e, 0x70, 0x63, 0x63, 0x2e, 0x70, 0x62, 0x2e, 0x6a, 0x61,
	0x76, 0x61, 0x5a, 0x06, 0x2e, 0x2f, 0x70, 0x62, 0x67, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_elect_proto_rawDescOnce sync.Once
	file_elect_proto_rawDescData = file_elect_proto_rawDesc
)

func file_elect_proto_rawDescGZIP() []byte {
	file_elect_proto_rawDescOnce.Do(func() {
		file_elect_proto_rawDescData = protoimpl.X.CompressGZIP(file_elect_proto_rawDescData)
	})
	return file_elect_proto_rawDescData
}

var file_elect_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_elect_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_elect_proto_goTypes = []interface{}{
	(Vote_Role)(0),               // 0: pbgo.Vote.Role
	(*Term)(nil),                 // 1: pbgo.Term
	(*Vote)(nil),                 // 2: pbgo.Vote
	(*BallotResponse)(nil),       // 3: pbgo.BallotResponse
	(*Identity)(nil),             // 4: pbgo.Identity
	(*Empt)(nil),                 // 5: pbgo.Empt
	(*ListResponse)(nil),         // 6: pbgo.ListResponse
	(*CalloutVoteResponse)(nil),  // 7: pbgo.CalloutVoteResponse
	(*CheckVoteBoxResponse)(nil), // 8: pbgo.CheckVoteBoxResponse
}
var file_elect_proto_depIdxs = []int32{
	0, // 0: pbgo.Vote.role:type_name -> pbgo.Vote.Role
	1, // 1: pbgo.Vote.term:type_name -> pbgo.Term
	4, // 2: pbgo.ListResponse.ids:type_name -> pbgo.Identity
	2, // 3: pbgo.Elect.Ballot:input_type -> pbgo.Vote
	4, // 4: pbgo.Elect.GetIdentity:input_type -> pbgo.Identity
	5, // 5: pbgo.Elect.List:input_type -> pbgo.Empt
	2, // 6: pbgo.Elect.CalloutVote:input_type -> pbgo.Vote
	2, // 7: pbgo.Elect.CheckVoteBox:input_type -> pbgo.Vote
	3, // 8: pbgo.Elect.Ballot:output_type -> pbgo.BallotResponse
	6, // 9: pbgo.Elect.GetIdentity:output_type -> pbgo.ListResponse
	6, // 10: pbgo.Elect.List:output_type -> pbgo.ListResponse
	7, // 11: pbgo.Elect.CalloutVote:output_type -> pbgo.CalloutVoteResponse
	8, // 12: pbgo.Elect.CheckVoteBox:output_type -> pbgo.CheckVoteBoxResponse
	8, // [8:13] is the sub-list for method output_type
	3, // [3:8] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_elect_proto_init() }
func file_elect_proto_init() {
	if File_elect_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_elect_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Term); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_elect_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Vote); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_elect_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BallotResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_elect_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Identity); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_elect_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empt); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_elect_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_elect_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CalloutVoteResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_elect_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckVoteBoxResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_elect_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_elect_proto_goTypes,
		DependencyIndexes: file_elect_proto_depIdxs,
		EnumInfos:         file_elect_proto_enumTypes,
		MessageInfos:      file_elect_proto_msgTypes,
	}.Build()
	File_elect_proto = out.File
	file_elect_proto_rawDesc = nil
	file_elect_proto_goTypes = nil
	file_elect_proto_depIdxs = nil
}
